### ISSUE TITLE
Hello bro. I want to use my DI container in my project without autowiring. Here is my problem please suggest me a solution

### ISSUE THREAD

**Issue by kingx619** [kanian/patterns#1]
class Container
{
    private $bindings=[];

    public function set($abstract,$factory)
    {
        $this->bindings[$abstract] = $factory;
    }

    public function get($abstract)
    {
        return $this->bindings[$abstract]($this);
    }
}

I am registering every dependency maually to make sure I always get the best speed of execution without using autowiring like this ---

$container->set(Application::class,function(Container $c){
    return new Application(c->get(Router::class));
});

However, I have a problem that whenever I try to get a new instance from the container using the get method . I always get a different instance and not a singleton.. So what i can change in the code to make it and register as singleton in my bindings array??

**Comment by kanian** [comment]
The easiest way would be to follow this https://patrick-assoa-adou.medium.com/a-generic-php-singleton-1985f17eeb6f : Make your class a singleton using the above solution before registering it to the DI.
Now, if you want to maintain class based inheritance use the code here: https://github.com/kanian/patterns.
